version: '3'

services:
  mssql:
    image: microsoft/mssql-server-linux:latest
    container_name: mssql
    environment:
      MSSQL_PID: Express
      ACCEPT_EULA: Y
      SA_PASSWORD: myStrongPassword1
    restart: unless-stopped
  tests:
    build:
      context: .
      dockerfile: ./Dockerfile-test
    environment: 
      - Database__ConnectionString=Server=mssql,1433;User=sa;Password=myStrongPassword1;Database=UniqueArticle_Test
      - UniqueArticles__SimilarityPercent=95